site_name: Serving Team Docs
theme:
  name: material
  logo: images/Victory-Logo-200-300x191.png
  favicon: images/Victory-Logo-200-300x191.png
  collapsed_navigation: false
docs_dir: serving-team-docs
nav:
  - Home: index.md
#  - Worship Guides:
#    - Basics: worship-guides/basics.md
#    - Advanced: worship-guides/advanced.md
#  - Outreach Programs:
#    - Local: outreach/local.md
#    - International: outreach/international.md
#  - Children's Ministry:
#    - Curriculum: childrens-ministry/curriculum.md
#    - Safety Guidelines: childrens-ministry/safety.md
#  - Small Groups:
#    - Leadership Guide: small-groups/leadership.md
#    - Discussion Topics: small-groups/topics.md
  - Multimedia Team:
    - Photography Guidelines: multimedia-team/photography.md
    - Videography Guidelines: multimedia-team/videography.md
  - Tech Team:
    - General Information: tech-team/general-info.md
    - Team Calendar: tech-team/calendar.md
    - ProPresenter Guide: tech-team/propresenter-guide.md
    - Livestream Guide: tech-team/livestream-guide.md
    - Video Camera Guide: tech-team/video-camera-guide.md
markdown_extensions:
  - attr_list
  - md_in_html
