name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs
      - name: Output root directory contents
        run: ls -l
      - name: Output serving-team-docs directory contents
        run: ls -l serving-team-docs
      - name: Check MkDocs version
        run: mkdocs --version
      - name: Build MkDocs site
        run: mkdocs build --clean
      - name: Output site directory contents
        run: ls -l ./site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/serving-team-docs
          force_orphan: true # Optional: Use this if you want to create a new orphan branch for the deployment